# Generated by Django 3.2.8 on 2021-12-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Etiqueta', 'verbose_name_plural': 'Etiquetas'},
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='false', upload_to='post'),
            preserve_default=False,
        ),
    ]
