# Generated by Django 3.2.8 on 2021-12-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
